services:
  - type: web
    name: david-acuna
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn nombre_proyecto.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
