services:
  - type: web
    name: david-acuna
    runtime: python
    pythonVersion: 3.10.11  # <- ¡Forzamos esta versión!
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev  # Necesario para PyAudio
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn sistema.wsgi:app
    envVars:
      - key: DEBUG
        value: "False"

